name: PermissionWhitelist
main: us.kohi.permissionwhitelist.PermissionWhitelist
version: 1.0-SNAPSHOT
author: chris752w
commands:
    wl:
        description: Reload configuration file
        usage: /<command>